x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "2"
services:
  dashboard:
    image: ghcr.io/nezhahq/nezha
    restart: always
    volumes:
      - ./data:/dashboard/data
    logging: *default-logging

  nginx:
    image: nginx:stable-alpine
    restart: always
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - dashboard
    logging: *default-logging

  tunnel:
    image: cloudflare/cloudflared
    restart: always
    command: tunnel run --protocol http2
    environment:
      - TUNNEL_TOKEN
    depends_on:
      - dashboard
    logging: *default-logging

  # watchtower:
  #   image: containrrr/watchtower
  #   restart: always
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   environment:
  #     - WATCHTOWER_DEBUG=true
  #     - WATCHTOWER_CLEANUP=true
  #     - WATCHTOWER_NOTIFICATIONS=shoutrrr
  #     - WATCHTOWER_NOTIFICATION_URL=telegram://${TELEGRAM_BOT_TOKEN}@telegram?chats=${TELEGRAM_CHAT_ID}
  #     - WATCHTOWER_POLL_INTERVAL=600
  #   logging: *default-logging

  # backup:
  #   image: ghcr.io/yumusb/autobackup:latest
  #   restart: always
  #   volumes:
  #     - ./:/app
  #   environment:
  #     - GITHUB_USER
  #     - GITHUB_TOKEN
  #     - GIT_REMOTE_URL
  #     - CRON_SCHEDULE